// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4hFeaydmKJjj2YbdfKsQzWMLrKzCswyY',
    appId: '1:214158396531:web:5371e579b1d5ddd862ee06',
    messagingSenderId: '214158396531',
    projectId: 'calendar-scheduler-20462',
    authDomain: 'calendar-scheduler-20462.firebaseapp.com',
    storageBucket: 'calendar-scheduler-20462.appspot.com',
    measurementId: 'G-K21RZC20K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Zu6OiWr9Y7BF9JZ2nxAUx1bP_Iw7JX4',
    appId: '1:214158396531:android:34cf5a143e7bc66062ee06',
    messagingSenderId: '214158396531',
    projectId: 'calendar-scheduler-20462',
    storageBucket: 'calendar-scheduler-20462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FhV-km86rGC5N6SXsYUMeLYVhkpbq2I',
    appId: '1:214158396531:ios:3a4ace82fa6feb6c62ee06',
    messagingSenderId: '214158396531',
    projectId: 'calendar-scheduler-20462',
    storageBucket: 'calendar-scheduler-20462.appspot.com',
    iosBundleId: 'com.example.flutterCalendarSchedulerFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_FhV-km86rGC5N6SXsYUMeLYVhkpbq2I',
    appId: '1:214158396531:ios:3a4ace82fa6feb6c62ee06',
    messagingSenderId: '214158396531',
    projectId: 'calendar-scheduler-20462',
    storageBucket: 'calendar-scheduler-20462.appspot.com',
    iosBundleId: 'com.example.flutterCalendarSchedulerFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4hFeaydmKJjj2YbdfKsQzWMLrKzCswyY',
    appId: '1:214158396531:web:9ef82a7c447c7dca62ee06',
    messagingSenderId: '214158396531',
    projectId: 'calendar-scheduler-20462',
    authDomain: 'calendar-scheduler-20462.firebaseapp.com',
    storageBucket: 'calendar-scheduler-20462.appspot.com',
    measurementId: 'G-WK5C450X1Q',
  );
}
